"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Table_1 = require("./Table");
Object.defineProperty(exports, "Table", { enumerable: true, get: function () { return Table_1.Table; } });
var TableBody_1 = require("./TableBody");
Object.defineProperty(exports, "TableBody", { enumerable: true, get: function () { return TableBody_1.TableBody; } });
var TableData_1 = require("./TableData");
Object.defineProperty(exports, "TableData", { enumerable: true, get: function () { return TableData_1.TableData; } });
var TableFoot_1 = require("./TableFoot");
Object.defineProperty(exports, "TableFoot", { enumerable: true, get: function () { return TableFoot_1.TableFoot; } });
var TableHead_1 = require("./TableHead");
Object.defineProperty(exports, "TableHead", { enumerable: true, get: function () { return TableHead_1.TableHead; } });
var TableHeader_1 = require("./TableHeader");
Object.defineProperty(exports, "TableHeader", { enumerable: true, get: function () { return TableHeader_1.TableHeader; } });
var TableRow_1 = require("./TableRow");
Object.defineProperty(exports, "TableRow", { enumerable: true, get: function () { return TableRow_1.TableRow; } });
