import { Meta } from '@storybook/react';
import './flex.scss';
declare const _default: Meta<import('@storybook/react').Args>;
export default _default;
export declare const Default: any;
export declare const Center: any;
export declare const Right: any;
export declare const Column: any;
export declare const ReverseColumn: any;
export declare const RowColumn: any;
export declare const Wrap: any;
